[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "google"
src_paths = ["meltingpot", "examples"]

[tool.black]
line-length = 80
target-version = ["py39"]
